#theme = "hex_toxic"
#theme = "catppuccin_mocha"
theme = "base16_transparent"

[keys.normal]
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
# swapping lines up and down is apparently complicated
C-up = [ "keep_primary_selection", "extend_to_line_bounds", "extend_line_above", "split_selection_on_newline", "select_mode", "goto_line_end_newline", "normal_mode", "rotate_selection_contents_forward", "keep_primary_selection" ]
C-down = [ "keep_primary_selection", "move_line_down", "extend_to_line_bounds", "extend_line_above", "split_selection_on_newline", "select_mode", "goto_line_end_newline", "normal_mode", "rotate_selection_contents_forward", "keep_primary_selection", "move_line_down" ]
#esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.backspace]
b = ":sh zellij run -f -- just build"
r = ":sh zellij run -f -- just run"
t = ":sh zellij run -f -- just test"
l = ":sh zellij run -f -- just lint"
s = ":sh zellij run -cf -- zsh"

# add things into space menu!
#[keys.normal.space]
#r = ":config-reload"
#w = ":write"
#q = ":quit"

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 16
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
#space = "all"
tab = "all"
newline = "none"

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]