#theme = "hex_toxic"
#theme = "catppuccin_mocha"
theme = "base16_transparent"

[keys.normal]
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 16
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
#space = "all"
tab = "all"
newline = "none"

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]