#theme = "hex_toxic"
theme = "catppuccin_mocha"

[keys.normal.backspace]
b = ":sh zellij run -f -- just build"
r = ":sh zellij run -f -- just run"
t = ":sh zellij run -f -- just test"
l = ":sh zellij run -f -- just lint"
s = ":sh zellij run -cf -- zsh"
c = ":config-reload"
f = ":theme tokyonight"
d = ":theme catppuccin_mocha_transparent"

[editor]
cursorline = true
color-modes = true
bufferline = "always"

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 16
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.lsp]
display-messages = true # progress on statusbar

# NB: cross reference binds with command palette (S-?)
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"] # comma is awkward for removing multi-caret

#"x" = "extend_to_line_bounds"
#"X" = "extend_line_below"
#"C-x" = "shrink_to_line_bounds"

# disable hjkl because colemak; neio is the equivalent colemak, but don't want to shift everything around..
# NB: tons more of this later
h = "no_op" # default: move_char_left
j = "no_op" # default: move_visual_line_down
k = "no_op" # default: move_visual_line_up
l = "no_op" # default: move_char_right

# move selections
#"C-down" = ["extend_to_line_bounds", "search_selection", "delete_selection", "move_line_down", "paste_before", "move_line_up", "goto_line_end", "search_next"]
#"C-up" = ["extend_to_line_bounds", "search_selection", "delete_selection", "move_line_up", "paste_before", "move_line_up", "goto_line_end", "search_next"]# NB: this limits command binds on mac when using modifier remap
# in particular have to remove ^-up bind for mission control, leaving the last mac native bind as: ^-space (spotlight)
# .. super is effectively unused in the terminal as a result of this
# maybe we pivot away from the standard modifiers in helix entirely?

#S = "surround_add"

# rebind some alt based keys to ctrl to avoid zellij clashes
"A-u" = "no_op" # previous: earlier
"A-U" = "no_op" # previous: later
"A-!" = "no_op" # previous: shell_apend_output
# word movement as in shell - might be a bad idea
"C-left" = "move_prev_word_end"
"C-S-left" = "move_prev_long_word_start"
"C-right" = "move_next_word_end"
"C-S-right" = "move_next_long_word_end"
"C-down" = ["half_page_down", "goto_window_center"]
"C-up" = ["half_page_up", "goto_window_center"]
"C-S-down" = ["page_down", "goto_window_center"]
"C-S-up" = ["page_up", "goto_window_center"]

[keys.select]
# word movement as in shell and normal mode
# TODO: paragraph or fn based movement?
"C-left" = "extend_prev_word_end"
"C-S-left" = "extend_prev_long_word_start"
"C-right" = "extend_next_word_end"
"C-S-right" = "extend_next_long_word_end"
"C-down" = ["half_page_down", "goto_window_center"]
"C-up" = ["half_page_up", "goto_window_center"]
"C-S-down" = ["page_down", "goto_window_center"]
"C-S-up" = ["page_up", "goto_window_center"]

# remaining effort to kill hjkl
[keys.normal.g]
h = "no_op"
j = "no_op"
l = "no_op"
k = "no_op"

[keys.normal.z]
j = "no_op"                   # default: scroll_down
k = "no_op"                   # default: scroll_up

[keys.normal.space.w]
h = "no_op"                   # default: jump_view_left
j = "no_op"                   # default: jump_view_down
k = "no_op"                   # default: jump_view_up
l = "no_op"                   # default: jump_view_right
H = "no_op"                   # default: swap_view_left
J = "no_op"                   # default: swap_view_down
K = "no_op"                   # default: swap_view_up
L = "no_op"                   # default: swap_view_right
[keys.normal.C-w]
h = "no_op"                   # default: jump_view_left
j = "no_op"                   # default: jump_view_down
k = "no_op"                   # default: jump_view_up
l = "no_op"                   # default: jump_view_right
H = "no_op"                   # default: swap_view_left
J = "no_op"                   # default: swap_view_down
K = "no_op"                   # default: swap_view_up
L = "no_op"                   # default: swap_view_right

# window
[keys.select.space.w]
h = "no_op"                   # default: jump_view_left
j = "no_op"                   # default: jump_view_down
k = "no_op"                   # default: jump_view_up
l = "no_op"                   # default: jump_view_right
C-h = "no_op"                 # default: jump_view_left
C-j = "no_op"                 # default: jump_view_down
C-k = "no_op"                 # default: jump_view_up
C-l = "no_op"                 # default: jump_view_right
H = "no_op"                   # default: swap_view_left
J = "no_op"                   # default: swap_view_down
K = "no_op"                   # default: swap_view_up
L = "no_op"                   # default: swap_view_right

#n = "hsplit_new"              # default: hsplit_new or vsplit_new menu

[keys.select.C-w]
h = "no_op"                   # default: jump_view_left
j = "no_op"                   # default: jump_view_down
k = "no_op"                   # default: jump_view_up
l = "no_op"                   # default: jump_view_right
C-h = "no_op"                 # default: jump_view_left
C-j = "no_op"                 # default: jump_view_down
C-k = "no_op"                 # default: jump_view_up
C-l = "no_op"                 # default: jump_view_right
H = "no_op"                   # default: swap_view_left
J = "no_op"                   # default: swap_view_down
K = "no_op"                   # default: swap_view_up
L = "no_op"                   # default: swap_view_right

