#theme = "hex_toxic"
#theme = "catppuccin_mocha"
theme = "base16_transparent"
# TODO: transparent bg: https://www.reddit.com/r/HelixEditor/comments/11f6scu/transparent_background/

[keys.normal.backspace]
b = ":sh zellij run -f -- just build"
r = ":sh zellij run -f -- just run"
t = ":sh zellij run -f -- just test"
l = ":sh zellij run -f -- just lint"
s = ":sh zellij run -cf -- zsh"
c = ":config-reload"
f = ":theme catppuccin_mocha"
d = ":theme tokyonight"

[editor]
cursorline = true
color-modes = true
bufferline = "always"

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 16
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.lsp]
display-messages = true # progress on statusbar

# NB: cross reference binds with command palette (S-?)
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"] # comma is awkward for removing multi-caret

#"x" = "extend_to_line_bounds"
#"X" = "extend_line_below"
#"C-x" = "shrink_to_line_bounds"

# rebind alt keys to ctrl where necessary WIP
"A-u" = "no_op" # previous: earlier
"A-U" = "no_op" # previous: later
"A-!" = "no_op" # previous: shell_apend_output
# word movement as in shell - might be a bad idea
"C-left" = "move_prev_word_end"
"C-S-left" = "move_prev_long_word_start"
"C-right" = "move_next_word_end"
"C-S-right" = "move_next_long_word_end"

# move selections
"C-down" = ["extend_to_line_bounds", "search_selection", "delete_selection", "move_line_down", "paste_before", "move_line_up", "goto_line_end", "search_next"]
"C-up" = ["extend_to_line_bounds", "search_selection", "delete_selection", "move_line_up", "paste_before", "move_line_up", "goto_line_end", "search_next"]# NB: this limits command binds on mac when using modifier remap
# in particular have to remove ^-up bind for mission control, leaving the last mac native bind as: ^-space (spotlight)
# .. super is effectively unused in the terminal as a result of this
# maybe we pivot away from the standard modifiers in helix entirely?

# disable hjkl because colemak; neio is the equivalent colemak, but don't want to shift everything around..
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"

[keys.normal.g]
h = "no_op"
j = "no_op"
l = "no_op"
k = "no_op"

[keys.normal.z]
h = "no_op"
j = "no_op"
l = "no_op"
k = "no_op"



[keys.select]
# word movement as in shell and normal mode TODO: currently this breaks selection?!
# maybe this is a bug based on: https://docs.helix-editor.com/keymap.html#select--extend-mode
#"C-left" = "move_prev_word_end"
#"C-S-left" = "move_prev_long_word_start"
#"C-right" = "move_next_word_end"
#"C-S-right" = "move_next_long_word_end"
#S = "surround_add"
