#theme = "hex_toxic"
#theme = "catppuccin_mocha"
theme = "base16_transparent"
# TODO: transparent bg: https://www.reddit.com/r/HelixEditor/comments/11f6scu/transparent_background/

[keys.normal.backspace]
b = ":sh zellij run -f -- just build"
r = ":sh zellij run -f -- just run"
t = ":sh zellij run -f -- just test"
l = ":sh zellij run -f -- just lint"
s = ":sh zellij run -cf -- zsh"
c = ":config-reload"
f = ":theme catppuccin_mocha"

# add things into space menu!
[keys.normal.space]
w = ":write"
#q = ":quit"

[editor]
cursorline = true
color-modes = true

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 16
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.lsp]
display-messages = true # progress on statusbar

# colemak
# neio is the equivalent colemak, but don't want to shift everything around..
[keys.normal]
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
[keys.normal.g]
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
