#theme = "hex_toxic"
theme = "catppuccin_mocha"

[keys.normal.backspace]
b = ":sh zellij run -f -- just build"
r = ":sh zellij run -f -- just run"
t = ":sh zellij run -f -- just test"
l = ":sh zellij run -f -- just lint"
s = ":sh zellij run -cf -- zsh"
c = ":config-reload"
f = ":theme tokyonight"
d = ":theme catppuccin_mocha_transparent"

[editor]
cursorline = true
color-modes = true
bufferline = "always"

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 16
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.lsp]
display-messages = true # progress on statusbar

# NB: cross reference binds with command palette (S-?)

[keys.insert]
# home/end replacement
"C-e" = ["goto_line_end", "move_char_right"]
"C-a" = "goto_line_start"
# line killing is more complicated:
#Alt-backspace = "kill_to_line_start" # works on mac, but then we lose word backward delete
#S-backspace = "delete_word_backward" # all other backspace variants fail on mac
# so we just rely on default C-u or C-k to delete to start or end of line:
#"C-u" = "kill_to_line_start" # default
#"C-k" = "kill_to_line_end" # default

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"] # comma is awkward for removing multi-caret
"C-e" = ["goto_line_end", "move_char_right"]
"C-a" = "goto_line_start" # previous: increment
"C-x" = "no_op" # previous: decrement

# select + search word under cursor (then use n or p - visual for multi) - basically A-up in select + *
"`" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection"] # previous: switch_to_lowercase
"A-`" = "no_op" # previous: switch_to_uppercase

# rebind some alt based keys to ctrl to avoid zellij clashes
"A-u" = "no_op" # previous: earlier
"A-U" = "no_op" # previous: later
"A-!" = "no_op" # previous: shell_apend_output

# experiments
#"x" = "extend_to_line_bounds"
#"X" = "extend_line_below"
#"C-x" = "shrink_to_line_bounds"
#S = "surround_add"
# move selections
#"C-down" = ["extend_to_line_bounds", "search_selection", "delete_selection", "move_line_down", "paste_before", "move_line_up", "goto_line_end", "search_next"]
#"C-up" = ["extend_to_line_bounds", "search_selection", "delete_selection", "move_line_up", "paste_before", "move_line_up", "goto_line_end", "search_next"]

# disable hjkl because colemak; neio is the equivalent colemak, but don't want to shift everything around..
# NB: tons more of this later
h = "no_op" # default: move_char_left
j = "no_op" # default: move_visual_line_down
k = "no_op" # default: move_visual_line_up
l = "no_op" # default: move_char_right

# word movement as in shell
# On mac, unbind all native keys (except ^-space for spotlight)
"C-left" = "move_prev_word_end"
"C-S-left" = "move_prev_long_word_start"
"C-right" = "move_next_word_end"
"C-S-right" = "move_next_long_word_end"
"C-down" = ["half_page_down", "goto_window_center"]
"C-up" = ["half_page_up", "goto_window_center"]
"C-S-down" = ["page_down", "goto_window_center"]
"C-S-up" = ["page_up", "goto_window_center"]
# NB: Alt-arrow movement defaults require zellij locked mode (C-g toggle)
# See https://github.com/zellij-org/zellij/issues/735
# Pertains to: A-{left,right,up,down} for sibling/hierarchical select in syntax tree

[keys.select]
# word movement as in shell and normal mode
# Alt-{left,right,up,down} for syntax based movement in zellij locked
"C-left" = "extend_prev_word_end"
"C-S-left" = "extend_prev_long_word_start"
"C-right" = "extend_next_word_end"
"C-S-right" = "extend_next_long_word_end"
"C-down" = ["half_page_down", "goto_window_center"]
"C-up" = ["half_page_up", "goto_window_center"]
"C-S-down" = ["page_down", "goto_window_center"]
"C-S-up" = ["page_up", "goto_window_center"]

[keys.normal.g]
# remaining effort to kill hjkl
h = "no_op"
j = "no_op"
l = "no_op"
k = "no_op"

[keys.normal.z]
j = "no_op"                   # default: scroll_down
k = "no_op"                   # default: scroll_up

[keys.normal.space.w]
h = "no_op"                   # default: jump_view_left
j = "no_op"                   # default: jump_view_down
k = "no_op"                   # default: jump_view_up
l = "no_op"                   # default: jump_view_right
H = "no_op"                   # default: swap_view_left
J = "no_op"                   # default: swap_view_down
K = "no_op"                   # default: swap_view_up
L = "no_op"                   # default: swap_view_right
[keys.normal.C-w]
h = "no_op"                   # default: jump_view_left
j = "no_op"                   # default: jump_view_down
k = "no_op"                   # default: jump_view_up
l = "no_op"                   # default: jump_view_right
H = "no_op"                   # default: swap_view_left
J = "no_op"                   # default: swap_view_down
K = "no_op"                   # default: swap_view_up
L = "no_op"                   # default: swap_view_right

# window
[keys.select.space.w]
h = "no_op"                   # default: jump_view_left
j = "no_op"                   # default: jump_view_down
k = "no_op"                   # default: jump_view_up
l = "no_op"                   # default: jump_view_right
C-h = "no_op"                 # default: jump_view_left
C-j = "no_op"                 # default: jump_view_down
C-k = "no_op"                 # default: jump_view_up
C-l = "no_op"                 # default: jump_view_right
H = "no_op"                   # default: swap_view_left
J = "no_op"                   # default: swap_view_down
K = "no_op"                   # default: swap_view_up
L = "no_op"                   # default: swap_view_right

#n = "hsplit_new"              # default: hsplit_new or vsplit_new menu

[keys.select.C-w]
h = "no_op"                   # default: jump_view_left
j = "no_op"                   # default: jump_view_down
k = "no_op"                   # default: jump_view_up
l = "no_op"                   # default: jump_view_right
C-h = "no_op"                 # default: jump_view_left
C-j = "no_op"                 # default: jump_view_down
C-k = "no_op"                 # default: jump_view_up
C-l = "no_op"                 # default: jump_view_right
H = "no_op"                   # default: swap_view_left
J = "no_op"                   # default: swap_view_down
K = "no_op"                   # default: swap_view_up
L = "no_op"                   # default: swap_view_right

