[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
# https://github.com/redhat-developer/yaml-language-server#language-server-settings
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/*/{tasks,handlers}/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible-lint-config.json" = ".ansible-lint"
"https://json.schemastore.org/circleciconfig.json" = ".circleci/config.yml"
#kubernetes = ["*.yaml"]
#"values.schema.json" = "values.yaml" -> helm charts must add an inline $schema=./values.schema.json instead

[language-server.mdpls]
# Experiment; this works once you install https://github.com/euclio/mdpls
# and add it to the markdown language: https://github.com/helix-editor/helix/blob/a069b928973aad99b85dffb9d5ade7dae4b58c43/languages.toml#L1375-L1382
# but it doesn't feel amazing
name = "markdown"
command = "mdpls"
config = { markdown.preview.auto = true, markdown.preview.browser = "firefox" }
