import = [
  "~/.config/alacritty/rose-pine.toml",
  "~/.config/alacritty/os.toml", # NB: symlinked to linux.toml or macos.toml via justfile
]

[env]
RUST_BACKTRACE = "1"

[font.bold]
family = "Inconsolata Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Inconsolata Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Inconsolata Nerd Font Mono"
style = "Regular"

[shell]
# start zellij with a small sleep to ensure it gets right dimensions
args = ["-ic", "sleep 0.2 && zellij -l compact"]
program = "zsh"

[window]
opacity = 0.8

[mouse]
hide_when_typing = true
