# https://github.com/alacritty/alacritty/blob/master/alacritty.yml
shell:
  program: zsh
  # start zellij with a small sleep to ensure it gets right dimensions
  args:
   - -ic
   - sleep 0.2 && zellij -l compact

env:
  RUST_BACKTRACE: "1"

import:
# NB: decent themes: nord, challenger_deep, wombat
- ~/.config/alacritty/rose-pine.yaml
# NB: This file is a symlink to either linux.yml or mac.yml (see justfile)
- ~/.config/alacritty/os.yml


window:
  startup_mode: Maximized
  opacity: 0.8
  # TODO: next version, can use alt-+ and alt-hjkl
  #option_as_alt: Both

font:
  size: 20
  normal:
    family: Inconsolata Nerd Font Mono
    style: Regular
  bold:
    family: Inconsolata Nerd Font Mono
    style: Bold
  italic:
    family: Inconsolata Nerd Font Mono
    style: Italic
