# https://github.com/alacritty/alacritty/blob/master/alacritty.yml
shell:
  program: zsh
  # start zellij with a small sleep to ensure it gets right dimensions
  args:
   - -ic
   - sleep 0.2 && zellij -l compact

env:
  RUST_BACKTRACE: "1"

import:
- ~/.config/alacritty/rose-pine.yaml
# NB: decent themes: nord, challenger_deep, wombat

window:
  startup_mode: Maximized
  decorations: buttonless # mac only
  decorations: none # linux
  opacity: 0.8
  # TODO: next version, can use alt-+ and alt-hjkl
  #option_as_alt: Both

key_bindings:
  - { key: F1, action: ToggleSimpleFullscreen } # NB: mac only

font:
  size: 20
  normal:
    family: Inconsolata Nerd Font Mono
    style: Regular
  bold:
    family: Inconsolata Nerd Font Mono
    style: Bold
  italic:
    family: Inconsolata Nerd Font Mono
    style: Italic
