[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "F2"

[[keyboard.bindings]]
mods = "Command"
key = "T"
action = "None"

[[keyboard.bindings]]
mods = "Command"
key = "N"
action = "None"

[font]
size = 28

[window]
decorations = "Buttonless" # mac only option
option_as_alt = "Both" # allow alt-+
startup_mode = "SimpleFullscreen"
