[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "F2"

[font]
size = 20

[window]
decorations = "Buttonless" # mac only option
option_as_alt = "Both" # allow alt-+
startup_mode = "SimpleFullscreen"
