language: haskell
sudo: false

ghc:
  - 7.8

notifications:
  email: false

before_script:
  - "cabal update"
  - "cabal install shellcheck"

script:
  - find . -maxdepth 1 -type f -name ".*" \
      | grep -vE "iface|gitconfig|intrc|yml" \
      | xargs shellcheck -e SC2046 -e SC2034 -e 2086
