language: haskell
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - cabal install shellcheck
env:
  - 'SHELLCHECK_OPTS="-e SC1091 -e SC1090 -s bash"'
script:
  - 'shellcheck .bashrc .aliases .exports .bash_pro* .functions .xprofile*'
