sudo: required
services:
  - docker
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - docker run \
    -e SHELLCHECK_OPTS="-e SC1091 -e SC1090 -e SC1117 -s bash" \
    -v $PWD:/volume -w /volume \
    -t koalaman/shellcheck:stable \
      .aliases .exports .bashrc .bash_completion .bash_profile .path .prompt .functions .xprofile
