language: haskell
sudo: false

notifications:
  email: false

install:
  - cabal install shellcheck

env:
  - SHELLCHECK_OPTS="-e SC1091 -s bash"

script:
  - shellcheck .bashrc .aliases .exports .bash_pro* .functions install* .xprofile*
