language: node_js
sudo: false
node_js:
  - 4
  - node
notifications:
  email:
    on_success: change
    on_failure: always
before_script:
  - npm link
after_success:
  - npm install coveralls
  - 'npm run coverage | coveralls'
