[package]
name = "mycrate"
version = "0.1.0"
authors = ["Eirik Albrigtsen <sszynrae@gmail.com>"]

[lib]
name = "mycrate"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/main.rs"
doc = false

[dependencies]
clap = "2.2.1"
rustc-serialize = "0.3"
