#!/usr/bin/env bash

# Spell check the commit message
if hash hunspell 2>/dev/null; then
  WORDS=$(grep -v '^#' "$1" | hunspell -l | tr '\n' '|')

  # Print commit message with all possible erroneous words highlighted
  if [ -n "$WORDS" ]; then

    HIGHLIGHTED=$( \
      grep -v '^#' "$1" | \
      egrep -w "${WORDS}" --color=always -A 100 -B 100 | \
      sed 's/\x1b\[m/\x1b\[1;30m/g')

    echo -e "Possible spelling errors found in commit message:"
    echo -e "\e[1;30m$HIGHLIGHTED\e[0m"
    echo -e "Use git commit --amend to change the commit message."
  fi

else

  echo "hunspell does not appear to be installed"

fi
