[preview]
syntect_theme = "~/.config/bat/themes/Catppuccin-mocha.tmTheme"

[opener]
#image = [
#  { exec = 'feh "$@"', desc = "Open" },
#]
video = [
  { exec = 'mpv "$@"' },
]
audio = [
  { exec = 'mpv "$@"' },
]
fallback = [
  { exec = 'open "$@"', desc = "Open" },
]
