[preview]
syntect_theme = "~/.config/bat/themes/Catppuccin-mocha.tmTheme"

[opener]
#folder = [
#  { exec = 'yazi "$@"', display_name = "Reveal in Finder" },
#]
image = [
  { exec = 'feh "$@"', display_name = "Open" },
]
video = [
  { exec = 'mpv "$@"' },
]
audio = [
  { exec = 'mpv "$@"' },
]
fallback = [
  { exec = 'xdg-open "$@"', display_name = "Open" },
]
