[preview]
syntect_theme = "~/.config/bat/themes/Catppuccin-mocha.tmTheme"

[manager]
sort_by = "alphabetical"
sort_dir_first = true
show_symlink = true
show_hidden = true

[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "play" },
	{ mime = "audio/*", use = "play" },

	{ mime = "application/json", use = "edit" },
	{ mime = "*/javascript",     use = "edit" },
  { mime = "*", use = "open" },
]

[opener]
edit = [
	{ exec = '$EDITOR "$@"', block = true,  for = "unix" },
]
image = [
  { exec = 'feh "$@"', desc = "feh", for = "linux" },
  { exec = 'open "$@"', desc = "Open", for = "macos" },
]
play = [
  { exec = 'mpv "$@"' },
]
open = [
	{ exec = 'xdg-open "$@"',             desc = "Open", for = "linux" },
	{ exec = 'open "$@"',                 desc = "Open", for = "macos" },
]
