name: lint

on:
  push:
    branches:
      - master

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    env:
      SHELLCHECK_OPTS: "-e SC1091 -e SC1090 -e SC1117 -s bash"
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2
    - uses: extractions/setup-just@v1
    - run: shellcheck --version
    - run: env | grep SHELLCHECK
    - run: just lint
