name: lint

on:
  push:
    branches:
      - master

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2

    - uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        image:  koalaman/shellcheck:stable
        options: -v ${{ github.workspace }}:/work
        run: make lint
